sike= '''H said,
1,293,493 views  Dec 8, 2022  Python for Beginners (Full Course) | #100DaysOfCode Programming Tutorial in Hindi
Python is one of the most demanded programming languages in the job market. Surprisingly, it is equally easy to learn and master  Python. This python tutorial for absolute beginners in Hindi series will focus on teaching you python concepts from the ground up. 
Access the Playlist:    • Python for Beginners (Full Course) | #100D...  
Link to the Repl: https://replit.com/@codewithharry/11-...
Join Replit the browser-based IDE used in this course - https://join.replit.com/code-with-har...
►Checkout my English channel here:    / @programmingwithharry  
►Instagram: www.instagram.com/codewithharry

python, C, C++, Java, JavaScript and Other Cheetsheets [++]:
Playlist:    • Coding CheatSheets 🧾 by CodeWithHarry  

►Learn in One Video[++]:
Python[15 Hr]:    • Python Tutorial For Beginners In Hindi (Wi...  
Python Advance[3.5 Hr]:    • Python Programming Course in Hindi (Advanc...  
Python[1 Hr]:    • Learn Python In Hindi In One Video - हिंदी...  
Python[2 Hr]:    • Python Tutorial In Hindi 🔥  
Python[15 Min]:   • 15 Minute Python Tutorial For Beginners In...  
JavaScript[1 Hr]:    • JavaScript Tutorial  
C[1.3 Hr]-   • C Programming Tutorial For Beginners: Lear...  
php[1 Hr]:    • Learn Php In One Video In Hindi - हिंदी में  
php[2.3 Hr]:   • Php Tutorial for Beginners in Hindi with M...  
php[Project]-    • Login And Registration Form Using Php & My...  
HTML[30 Min]:   • HTML 5 Tutorial For Beginners In Hindi - ह...  
CSS[8.5 Hr]:   • CSS Tutorial In Hindi (With Notes) 🔥  
CSS[1.4 Hr]:   • CSS 3 Tutorial For Beginners: Learn CSS In...  
Wordpress[3.2 Hr]:   • How To Make a WordPress Website | Wordpres...  
Angular[2 Hr]:   • Angular Tutorial in Hindi  
Java[2.3 Hr]:   • Java tutorial in hindi 🔥  
Web Scraping[1 Hr]:   • Web Scraping Tutorial using Python and Bea...  
MongoDB[2 Hr]:   • MongoDb Tutorial For Beginners in Hindi 🔥🔥  
Numpy[1 Hr]:   • Numpy Tutorial in Hindi  
Android Dev[12 Hr]-    • Android Development Tutorial For Beginners...  
Linux[1 Hr]:   • Linux Tutorial For Beginners in Hindi  
JQuery[1.1 Hr]:   • jQuery Tutorial For Beginners In Hindi - ह...  
Git and GitHub[1.1 Hr]:   • Git & GitHub Tutorial For Beginners In Hin...  

►Complete course [playlist]:
React:    • React Js Tutorials in Hindi  
Python-   • Python Tutorials For Absolute Beginners In...  
OOP Python-   • Object Oriented Programming Tutorials Usin...  
Java:   • Java Tutorials For Beginners In Hindi  
JavaScript-    • JavaScript Tutorials In Hindi  
PHP-   • PHP Tutorials in Hindi  
C-   • C Language Tutorials In Hindi  
C++-   • C++ Tutorials In Hindi  
Git & GitHub-   • Git and GitHub Tutorials In Hindi  
Android Dev-    • Android Development Tutorials in Hindi  
Python GUI-    • Python GUI: Tkinter Tutorial In Hindi  
Web Development-    • Web Development Tutorials For Beginners In...  
Python Django:   • Python Django Tutorials In Hindi  
Projects Using HTML, CSS & Javascript-    • Projects Using HTML, CSS & JavaScript in H...  
Data Structure and Algo:   • Data Structures and Algorithms Course in H...   

Follow Me On Social Media
►Website (created using Django Rest & Angular): https://www.codewithharry.com
►Facebook:   / codewithharry  
►Instagram:   / codewithharry   
Twitter:   / codewithharry  
Comment "#HarryBhai" if you read this 😉😉'''

 print(sike))